import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className='flex justify-between border-b-2 border-gray-800 text-xl p-2'>
            <Link href='/'>
                <p>Logos</p>
            </Link>
            <div className='flex space-x-6'>
                <Link href='/'>
                    <p>Home</p>
                </Link>
                <Link href='/projects'>
                    <p>Projects</p>
                </Link>
                <Link href='/faq'>
                    <p>FAQ</p>
                </Link>
                <Link href='/contact'>
                    <p>Contact</p>
                </Link>
                <Link href='/about'>
                    <p>About</p>
                </Link>
            </div>

        </div>
        {children}
        </body>
        </html>
    )
}
